# ============================================================
# Kustomize â€” Base
# ============================================================

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloudcart

resources:
  - ../../manifests/namespace.yml
  - ../../manifests/config.yml
  - ../../manifests/auth-service.yml
  - ../../manifests/product-service.yml
  - ../../manifests/order-service.yml
  - ../../manifests/network-policies.yml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: cloudcart
